export const legalshieldData = [
  {
    disabled: false,
    language: 'en',
    market: 'US',
    productDetails: [{ cost: '$29.95', name: 'Legal Plan', shortCode: 'LPUS21', term: 'Monthly', type: 'LegalShield' }],
    regions: ['New York'],
    term: 'Monthly',
    termTotal: '$29.95',
    testCaseName: 'Legal Plan, Existing User',
    userType: 'Existing',
  },
  {
    disabled: false,
    language: 'en',
    market: 'US',
    productDetails: [{ cost: '$29.95', name: 'Legal Plan', shortCode: 'LPUS21', term: 'Monthly', type: 'LegalShield' }],
    regions: ['Florida'],
    term: 'Monthly',
    termTotal: '$29.95',
    testCaseName: 'Legal Plan, New User',
    userType: 'New',
  },
  {
    disabled: false,
    language: 'en',
    market: 'US',
    productDetails: [
      { cost: '$29.95', name: 'Legal Plan', shortCode: 'LPUS21', term: 'Monthly', type: 'LegalShield' },
      {
        cost: '$14.95',
        name: 'Home Business Supplement',
        shortCode: 'HB3',
        term: 'Monthly',
        type: 'LegalShield',
      },
      {
        cost: '$14.95',
        name: 'Trial Defense Supplement',
        shortCode: 'TD3',
        term: 'Monthly',
        type: 'LegalShield',
      },

      {
        cost: '$14.95',
        name: 'Gun Owners Supplement',
        shortCode: 'GO2',
        term: 'Monthly',
        type: 'LegalShield',
      },
      {
        cost: '$14.95',
        name: 'Ride Share and Delivery Supplement',
        shortCode: 'RS2',
        term: 'Monthly',
        type: 'LegalShield',
      },
    ],
    regions: ['California'],
    term: 'Monthly',
    termTotal: '$89.75',
    testCaseName: 'Legal Plan, All Supplements',
    userType: 'Existing',
  },
  {
    disabled: false,
    language: 'en',
    market: 'US',
    productDetails: [{ cost: '$49.00', name: 'Small Business Legal Essentials', shortCode: 'ESS', term: 'Monthly', type: 'LegalShield' }],
    regions: ['Florida'],
    term: 'Monthly',
    termTotal: '$49.00',
    testCaseName: 'Small Business Legal Essentials, Existing User',
    userType: 'Existing',
  },
  {
    disabled: false,
    language: 'en',
    market: 'US',
    productDetails: [
      { cost: '$49.00', name: 'Small Business Legal Essentials', shortCode: 'ESS', term: 'Monthly', type: 'LegalShield' },
      { cost: '$29.95', name: 'Legal Plan', shortCode: 'LPUS21', term: 'Monthly', type: 'LegalShield' },
    ],
    regions: ['Colorado'],
    term: 'Monthly',
    termTotal: '$78.95',
    testCaseName: 'Small Business Legal Essentials + Legal Plan, Existing User',
    userType: 'Existing',
  },
  {
    disabled: false,
    language: 'en',
    market: 'US',
    productDetails: [
      { cost: '$49.00', name: 'Small Business Legal Essentials', shortCode: 'ESS', term: 'Monthly', type: 'LegalShield' },
      { cost: '$29.95', name: 'Legal Plan', shortCode: 'LPUS21', term: 'Monthly', type: 'LegalShield' },
      {
        cost: '$14.95',
        name: 'Home Business Supplement',
        shortCode: 'HB3',
        term: 'Monthly',
        type: 'LegalShield',
      },
      {
        cost: '$14.95',
        name: 'Trial Defense Supplement',
        shortCode: 'TD3',
        term: 'Monthly',
        type: 'LegalShield',
      },

      {
        cost: '$14.95',
        name: 'Gun Owners Supplement',
        shortCode: 'GO2',
        term: 'Monthly',
        type: 'LegalShield',
      },
      {
        cost: '$14.95',
        name: 'Ride Share and Delivery Supplement',
        shortCode: 'RS2',
        term: 'Monthly',
        type: 'LegalShield',
      },
    ],
    regions: ['Colorado'],
    term: 'Monthly',
    termTotal: '$138.75',
    testCaseName: 'Small Business Legal Essentials + Legal Plan + All Supplements, Existing User',
    userType: 'Existing',
  },
  {
    disabled: false,
    language: 'en',
    market: 'US',
    productDetails: [{ cost: '$99.00', name: 'Small Business Legal Plus', shortCode: 'PLUS', term: 'Monthly', type: 'LegalShield' }],
    regions: ['Ohio'],
    term: 'Monthly',
    termTotal: '$99.00',
    testCaseName: 'Small Business Legal Plus, Existing User',
    userType: 'Existing',
  },
  {
    disabled: false,
    language: 'en',
    market: 'US',
    productDetails: [
      { cost: '$99.00', name: 'Small Business Legal Plus', shortCode: 'PLUS', term: 'Monthly', type: 'LegalShield' },
      { cost: '$29.95', name: 'Legal Plan', shortCode: 'LPUS21', term: 'Monthly', type: 'LegalShield' },
    ],
    regions: ['Ohio'],
    term: 'Monthly',
    termTotal: '$128.95',
    testCaseName: 'Small Business Legal Plus + Legal Plan, Existing User',
    userType: 'Existing',
  },
  {
    disabled: false,
    language: 'en',
    market: 'US',
    productDetails: [
      { cost: '$99.00', name: 'Small Business Legal Plus', shortCode: 'PLUS', term: 'Monthly', type: 'LegalShield' },
      { cost: '$29.95', name: 'Legal Plan', shortCode: 'LPUS21', term: 'Monthly', type: 'LegalShield' },
      {
        cost: '$14.95',
        name: 'Home Business Supplement',
        shortCode: 'HB3',
        term: 'Monthly',
        type: 'LegalShield',
      },
      {
        cost: '$14.95',
        name: 'Trial Defense Supplement',
        shortCode: 'TD3',
        term: 'Monthly',
        type: 'LegalShield',
      },

      {
        cost: '$14.95',
        name: 'Gun Owners Supplement',
        shortCode: 'GO2',
        term: 'Monthly',
        type: 'LegalShield',
      },
      {
        cost: '$14.95',
        name: 'Ride Share and Delivery Supplement',
        shortCode: 'RS2',
        term: 'Monthly',
        type: 'LegalShield',
      },
    ],
    regions: ['Ohio'],
    term: 'Monthly',
    termTotal: '$188.75',
    testCaseName: 'Small Business Legal Plus + Legal Plan + All Supplements, Existing User',
    userType: 'Existing',
  },
  {
    disabled: false,
    language: 'en',
    market: 'US',
    productDetails: [{ cost: '$169.00', name: 'Small Business Legal Pro', shortCode: 'PRO', term: 'Monthly', type: 'LegalShield' }],
    regions: ['Virginia'],
    term: 'Monthly',
    termTotal: '$169.00',
    testCaseName: 'Small Business Legal Pro, Existing User',
    userType: 'Existing',
  },
  {
    disabled: false,
    language: 'en',
    market: 'US',
    productDetails: [
      { cost: '$169.00', name: 'Small Business Legal Pro', shortCode: 'PRO', term: 'Monthly', type: 'LegalShield' },
      { cost: '$29.95', name: 'Legal Plan', shortCode: 'LPUS21', term: 'Monthly', type: 'LegalShield' },
    ],
    regions: ['Illinois'],
    term: 'Monthly',
    termTotal: '$198.95',
    testCaseName: 'Small Business Legal Pro + Legal Plan, Existing User',
    userType: 'Existing',
  },
  {
    disabled: false,
    language: 'en',
    market: 'US',
    productDetails: [
      { cost: '$169.00', name: 'Small Business Legal Pro', shortCode: 'PRO', term: 'Monthly', type: 'LegalShield' },
      { cost: '$29.95', name: 'Legal Plan', shortCode: 'LPUS21', term: 'Monthly', type: 'LegalShield' },
      {
        cost: '$14.95',
        name: 'Home Business Supplement',
        shortCode: 'HB3',
        term: 'Monthly',
        type: 'LegalShield',
      },
      {
        cost: '$14.95',
        name: 'Trial Defense Supplement',
        shortCode: 'TD3',
        term: 'Monthly',
        type: 'LegalShield',
      },

      {
        cost: '$14.95',
        name: 'Gun Owners Supplement',
        shortCode: 'GO2',
        term: 'Monthly',
        type: 'LegalShield',
      },
      {
        cost: '$14.95',
        name: 'Ride Share and Delivery Supplement',
        shortCode: 'RS2',
        term: 'Monthly',
        type: 'LegalShield',
      },
    ],
    regions: ['Florida'],
    term: 'Monthly',
    termTotal: '$258.75',
    testCaseName: 'Small Business Legal Pro + Legal Plan + All Supplements, Existing User',
    userType: 'Existing',
  },
];
