export const shieldAssociateMultiSelectData = [
  {
    disabled: false,
    market: 'United States - English',
    paymentMethod: 'bank draft',
    planDetails: [
      {
        associateRegistrationType: 'NA',
        cost: '$29.95',
        marketingName: 'Legal Plan Family',
        name: 'Legal Plan Family',
        oneTimeFee: 'NA',
        shortCode: 'LPUS21',
        supplements: [],
        term: 'Monthly',
        tier: { cost: 'NA', name: 'NA' },
        type: 'LegalShield',
      },
    ],
    regions: ['Colorado'],
    termTotal: '$29.95',
    testCaseName: 'Legal Plan Family',
    userType: 'New',
  },
  {
    disabled: false,
    market: 'United States - English',
    paymentMethod: 'bank draft',
    planDetails: [
      {
        associateRegistrationType: 'NA',
        cost: '$29.95',
        marketingName: 'Legal Plan Family',
        name: 'Legal Plan Family',
        oneTimeFee: 'NA',
        shortCode: 'LPUS21',
        supplements: [
          { cost: '$14.95', name: 'Home Business Supplement' },
          {
            cost: '$14.95',
            name: 'Trial Defense Supplement',
          },
          {
            cost: '$14.95',
            name: 'Gun Owners Supplement',
          },
          {
            cost: '$14.95',
            name: 'Ride Share & Delivery Drivers Supplement',
          },
        ],
        term: 'Monthly',
        tier: { cost: 'NA', name: 'NA' },
        type: 'LegalShield',
      },
    ],
    regions: ['Colorado'],
    termTotal: '$89.75',
    testCaseName: 'Legal Plan Family - All Supplements',
    userType: 'New',
  },
  {
    disabled: false,
    market: 'United States - English',
    paymentMethod: 'bank draft',
    planDetails: [
      {
        associateRegistrationType: 'NA',
        cost: '$29.95',
        marketingName: 'IDShield Family',
        name: 'IDShield Family',
        oneTimeFee: 'NA',
        shortCode: 'TBD',
        supplements: [],
        term: 'Monthly',
        tier: { cost: '$0.00', name: '1 Bureau Credit Monitoring' },
        type: 'Identity Plan',
      },
    ],
    regions: ['Colorado'],
    termTotal: '$29.95',
    testCaseName: 'IdShield Family - 1 Bureau Credit Monitoring',
    userType: 'New',
  },
  {
    disabled: false,
    market: 'United States - English',
    paymentMethod: 'bank draft',
    planDetails: [
      {
        associateRegistrationType: 'NA',
        cost: '$29.95',
        marketingName: 'IDShield Family',
        name: 'IDShield Family',
        oneTimeFee: 'NA',
        shortCode: 'TBD',
        supplements: [],
        term: 'Monthly',
        tier: { cost: '$5.00', name: '3 Bureau Credit Monitoring' },
        type: 'Identity Plan',
      },
    ],
    regions: ['Colorado'],
    termTotal: '$34.95',
    testCaseName: 'IdShield Family - 3 Bureau Credit Monitoring',
    userType: 'New',
  },
  {
    disabled: false,
    market: 'United States - English',
    paymentMethod: 'bank draft',
    planDetails: [
      {
        associateRegistrationType: 'NA',
        cost: '$14.95',
        marketingName: 'IDShield Individual',
        name: 'IDShield Individual',
        oneTimeFee: 'NA',
        shortCode: 'TBD',
        supplements: [],
        term: 'Monthly',
        tier: { cost: '$0.00', name: '1 Bureau Credit Monitoring' },
        type: 'Identity Plan',
      },
    ],
    regions: ['Colorado'],
    termTotal: '$14.95',
    testCaseName: 'IdShield Individual - 1 Bureau Credit Monitoring',
    userType: 'New',
  },
  {
    disabled: false,
    market: 'United States - English',
    paymentMethod: 'bank draft',
    planDetails: [
      {
        associateRegistrationType: 'NA',
        cost: '$14.95',
        marketingName: 'IDShield Individual',
        name: 'IDShield Individual',
        oneTimeFee: 'NA',
        shortCode: 'TBD',
        supplements: [],
        term: 'Monthly',
        tier: { cost: '$5.00', name: '3 Bureau Credit Monitoring' },
        type: 'Identity Plan',
      },
    ],
    regions: ['Colorado'],
    termTotal: '$19.95',
    testCaseName: 'IdShield Individual - 3 Bureau Credit Monitoring',
    userType: 'New',
  },
  {
    disabled: false,
    market: 'United States - English',
    paymentMethod: 'bank draft',
    planDetails: [
      {
        associateRegistrationType: 'NA',
        cost: '$49',
        marketingName: 'Small Business',
        name: 'Small Business',
        oneTimeFee: 'NA',
        shortCode: 'TBD',
        supplements: [],
        term: 'Monthly',
        tier: { cost: '$0.00', name: 'Essentials Plan' },
        type: 'Legal Plan',
      },
    ],
    regions: ['Colorado'],
    termTotal: '$49.00',
    testCaseName: 'Small Business - Business Essentials Supplement',
    userType: 'New',
  },
  {
    disabled: false,
    market: 'United States - English',
    paymentMethod: 'bank draft',
    planDetails: [
      {
        associateRegistrationType: 'NA',
        cost: '$49',
        marketingName: 'Small Business',
        name: 'Small Business',
        oneTimeFee: 'NA',
        shortCode: 'TBD',
        supplements: [],
        term: 'Monthly',
        tier: { cost: '$50.00', name: 'Plus Plan' },
        type: 'Legal Plan',
      },
    ],
    regions: ['Colorado'],
    termTotal: '$99.00',
    testCaseName: 'Small Business - Business Plus Supplement',
    userType: 'New',
  },
  {
    disabled: false,
    market: 'United States - English',
    paymentMethod: 'bank draft',
    planDetails: [
      {
        associateRegistrationType: 'NA',
        cost: '$49',
        marketingName: 'Small Business',
        name: 'Small Business',
        oneTimeFee: 'NA',
        shortCode: 'TBD',
        supplements: [],
        term: 'Monthly',
        tier: { cost: '$120.00', name: 'Pro Plan' },
        type: 'Legal Plan',
      },
    ],
    regions: ['Colorado'],
    termTotal: '$169.00',
    testCaseName: 'Small Business - Business Pro Supplement',
    userType: 'New',
  },
  {
    disabled: false,
    market: 'United States - English',
    paymentMethod: 'bank draft',
    planDetails: [
      {
        associateRegistrationType: 'individual',
        cost: '$0.00',
        marketingName: 'Associate',
        name: 'Legalshield Advantage Plus',
        oneTimeFee: '$49',
        shortCode: 'TBD',
        supplements: [],
        term: 'One Time',
        tier: { cost: 'NA', name: 'NA' },
        type: 'Associate',
      },
    ],
    regions: ['Colorado'],
    termTotal: '$0.00',
    testCaseName: 'Associate - LegalShield Advantage Plus',
    userType: 'New',
  },
  {
    disabled: false,
    market: 'United States - English',
    paymentMethod: 'bank draft',
    planDetails: [
      {
        associateRegistrationType: 'NA',
        cost: '$32.95',
        marketingName: 'Commercial Drivers Legal Plan',
        name: 'Commercial Drivers Legal Plan',
        oneTimeFee: '$25.00',
        shortCode: 'TBD',
        supplements: [],
        term: 'Monthly',
        tier: { cost: 'NA', name: 'NA' },
        type: 'Legal Plan',
      },
    ],
    regions: ['Colorado'],
    termTotal: '$32.95',
    testCaseName: 'Commercial Drivers Legal Plan',
    userType: 'New',
  },
  {
    disabled: false,
    market: 'United States - English',
    paymentMethod: 'bank draft',
    planDetails: [
      {
        associateRegistrationType: 'NA',
        cost: '$44.95',
        marketingName: 'Super Commercial Drivers Legal Plan',
        name: 'Super Commercial Drivers Legal Plan',
        oneTimeFee: '$10.00',
        shortCode: 'TBD',
        supplements: [],
        term: 'Monthly',
        tier: { cost: 'NA', name: 'NA' },
        type: 'Legal Plan',
      },
    ],
    regions: ['Colorado'],
    termTotal: '$44.95',
    testCaseName: 'Super Commercial Drivers Legal Plan',
    userType: 'New',
  },
  {
    disabled: false,
    market: 'United States - English',
    paymentMethod: 'bank draft',
    planDetails: [
      {
        associateRegistrationType: 'NA',
        cost: '$29.95',
        marketingName: 'Legal Plan Family',
        name: 'Legal Plan Family',
        oneTimeFee: 'NA',
        shortCode: 'LPUS21',
        supplements: [
          { cost: '$14.95', name: 'Home Business Supplement' },
          {
            cost: '$14.95',
            name: 'Trial Defense Supplement',
          },
          {
            cost: '$14.95',
            name: 'Gun Owners Supplement',
          },
          {
            cost: '$14.95',
            name: 'Ride Share & Delivery Drivers Supplement',
          },
        ],
        term: 'Monthly',
        tier: { cost: 'NA', name: 'NA' },
        type: 'LegalShield',
      },
      {
        associateRegistrationType: 'NA',
        cost: '$14.95',
        marketingName: 'IDShield Individual',
        name: 'IDShield Individual',
        oneTimeFee: 'NA',
        shortCode: 'TBD',
        supplements: [],
        term: 'Monthly',
        tier: { cost: '$0.00', name: '1 Bureau Credit Monitoring' },
        type: 'Identity Plan',
      },
      {
        associateRegistrationType: 'NA',
        cost: '$49',
        marketingName: 'Small Business',
        name: 'Small Business',
        oneTimeFee: 'NA',
        shortCode: 'TBD',
        supplements: [],
        term: 'Monthly',
        tier: { cost: '$0.00', name: 'Essentials Plan' },
        type: 'Legal Plan',
      },
      {
        associateRegistrationType: 'individual',
        cost: '$0.00',
        marketingName: 'Associate',
        name: 'Legalshield Advantage Plus',
        oneTimeFee: '$49',
        shortCode: 'TBD',
        supplements: [],
        term: 'One Time',
        tier: { cost: 'NA', name: 'NA' },
        type: 'Associate',
      },
      {
        associateRegistrationType: 'NA',
        cost: '$44.95',
        marketingName: 'Super Commercial Drivers Legal Plan',
        name: 'Super Commercial Drivers Legal Plan',
        oneTimeFee: '$10.00',
        shortCode: 'TBD',
        supplements: [],
        term: 'Monthly',
        tier: { cost: 'NA', name: 'NA' },
        type: 'Legal Plan',
      },
    ],
    regions: ['Colorado'],
    termTotal: '$198.65',
    testCaseName: 'All Plans - All Supplements',
    userType: 'New',
  },
];
