/* eslint-disable sort-keys-fix/sort-keys-fix */
/* eslint-disable sort-keys */
export const headerThreeLinksData = [
  {
    testCaseName: 'Verify the Plans/Personal & Family/Coverage and Pricing link',
    firstLevelLink: 'Plans',
    secondLevelLink: 'Personal & Family',
    thirdLevelLink: 'Coverage & Pricing',
    expectedUrl: 'legalshield.com/personal-plan/coverage-and-pricing/',
    disabled: false,
  },
  {
    testCaseName: 'Verify the Plans/Personal & Family/Plan Details link',
    firstLevelLink: 'Plans',
    secondLevelLink: 'Personal & Family',
    thirdLevelLink: 'Plan Details',
    expectedUrl: 'legalshield.com/personal-plan/plan-details/',
    disabled: false,
  },
  {
    testCaseName: 'Verify the Plans/Personal & Family/FAQ link',
    firstLevelLink: 'Plans',
    secondLevelLink: 'Personal & Family',
    thirdLevelLink: 'FAQ',
    expectedUrl: 'legalshield.com/personal-plan/faq/',
    disabled: false,
  },
  {
    testCaseName: 'Verify the Plans/Personal & Family/How it Works link',
    firstLevelLink: 'Plans',
    secondLevelLink: 'Personal & Family',
    thirdLevelLink: 'How it Works',
    expectedUrl: 'legalshield.com/why-legalshield/how-it-works/',
    disabled: false,
  },
  {
    testCaseName: 'Verify the Plans/Run a Business/Coverage and Pricing link',
    firstLevelLink: 'Plans',
    secondLevelLink: 'Run a Business',
    thirdLevelLink: 'Coverage and Pricing', // and or &?
    expectedUrl: 'legalshield.com/business-plan/coverage-pricing/',
    disabled: false,
  },
  {
    testCaseName: 'Verify the Plans/Run a Business/Plan Details link',
    firstLevelLink: 'Plans',
    secondLevelLink: 'Run a Business',
    thirdLevelLink: 'Plan Details',
    expectedUrl: 'legalshield.com/business-plan/plan-summary/',
    disabled: false,
  },
  {
    testCaseName: 'Verify the Plans/Run a Business/FAQ link',
    firstLevelLink: 'Plans',
    secondLevelLink: 'Run a Business',
    thirdLevelLink: 'FAQ',
    expectedUrl: 'legalshield.com/business-plan/faq/',
    disabled: false,
  },
  {
    testCaseName: 'Verify the Plans/Run a Business/How it Works link',
    firstLevelLink: 'Plans',
    secondLevelLink: 'Run a Business',
    thirdLevelLink: 'How it Works',
    expectedUrl: 'legalshield.com/why-legalshield/how-it-works/',
    disabled: false,
  },
  {
    testCaseName: 'Verify the Plans/Commercial Drivers/Plan Details link',
    firstLevelLink: 'Plans',
    secondLevelLink: 'Commercial Drivers',
    thirdLevelLink: 'Plan Details',
    expectedUrl: 'legalshield.com/legal-protection-truck-drivers-and-other-commercial-drivers/',
    disabled: false,
  },
  {
    testCaseName: 'Verify the Personal/Estate Planning/Estate Planning Matters link',
    firstLevelLink: 'Personal',
    secondLevelLink: 'Estate Planning',
    thirdLevelLink: 'Estate Planning Matters',
    expectedUrl: 'legalshield.com/estate-planning/',
    disabled: false,
  },
  {
    testCaseName: 'Verify the Personal/Estate Planning/Last Will and Testament link',
    firstLevelLink: 'Personal',
    secondLevelLink: 'Estate Planning',
    thirdLevelLink: 'Last Will and Testament',
    expectedUrl: 'legalshield.com/estate-planning/last-will-and-testament/',
    disabled: false,
  },
  {
    testCaseName: 'Verify the Personal/Estate Planning/Power of Attorney link',
    firstLevelLink: 'Personal',
    secondLevelLink: 'Estate Planning',
    thirdLevelLink: 'Power of Attorney',
    expectedUrl: 'legalshield.com/estate-planning/power-of-attorney/',
    disabled: false,
  },
  {
    testCaseName: 'Verify the Personal/Estate Planning/Trusts link',
    firstLevelLink: 'Personal',
    secondLevelLink: 'Estate Planning',
    thirdLevelLink: 'Trusts',
    expectedUrl: 'legalshield.com/estate-planning/trusts/',
    disabled: false,
  },
  {
    testCaseName: 'Verify the Personal/Estate Planning/Probate link',
    firstLevelLink: 'Personal',
    secondLevelLink: 'Estate Planning',
    thirdLevelLink: 'Probate',
    expectedUrl: 'legalshield.com/estate-planning/probate/',
    disabled: false,
  },
  {
    testCaseName: 'Verify the Personal/Consumer Finance/Consumer Finance Matters link',
    firstLevelLink: 'Personal',
    secondLevelLink: 'Consumer Finance',
    thirdLevelLink: 'Consumer Finance Matters',
    expectedUrl: 'legalshield.com/consumer-finance/',
    disabled: false,
  },
  {
    testCaseName: 'Verify the Personal/Real Estate/Real Estate Matters link',
    firstLevelLink: 'Personal',
    secondLevelLink: 'Real Estate',
    thirdLevelLink: 'Real Estate Matters',
    expectedUrl: 'legalshield.com/real-estate/',
    disabled: false,
  },
  {
    testCaseName: 'Verify the Personal/Renters/Renter Matters link',
    firstLevelLink: 'Personal',
    secondLevelLink: 'Renters',
    thirdLevelLink: 'Renter Matters',
    expectedUrl: 'legalshield.com/renters/',
    disabled: false,
  },
  {
    testCaseName: 'Verify the Personal/Renters/Signing a Lease link',
    firstLevelLink: 'Personal',
    secondLevelLink: 'Renters',
    thirdLevelLink: 'Signing a Lease',
    expectedUrl: 'legalshield.com/renters/signing-a-lease/',
    disabled: false,
  },
  {
    testCaseName: 'Verify the Personal/Renters/Evictions link',
    firstLevelLink: 'Personal',
    secondLevelLink: 'Renters',
    thirdLevelLink: 'Evictions',
    expectedUrl: 'legalshield.com/renters/eviction-notice/',
    disabled: false,
  },
  {
    testCaseName: 'Verify the Personal/Renters/Security Deposits link',
    firstLevelLink: 'Personal',
    secondLevelLink: 'Renters',
    thirdLevelLink: 'Security Deposits',
    expectedUrl: 'legalshield.com/renters/security-deposit/',
    disabled: false,
  },
  {
    testCaseName: 'Verify the Personal/Renters/Terminating a Lease link',
    firstLevelLink: 'Personal',
    secondLevelLink: 'Renters',
    thirdLevelLink: 'Terminating a Lease',
    expectedUrl: 'legalshield.com/renters/lease-termination/',
    disabled: false,
  },
  {
    testCaseName: 'Verify the Personal/Landlords/Landlord Matters link',
    firstLevelLink: 'Personal',
    secondLevelLink: 'Landlords',
    thirdLevelLink: 'Landlord Matters',
    expectedUrl: 'legalshield.com/landlords/',
    disabled: false,
  },
  {
    testCaseName: 'Verify the Personal/Landlords/Negotiating Leases',
    firstLevelLink: 'Personal',
    secondLevelLink: 'Landlords',
    thirdLevelLink: 'Negotiating Leases',
    expectedUrl: 'legalshield.com/landlords/negotiating-leases/',
    disabled: false,
  },
  {
    testCaseName: 'Verify the Personal/Landlords/Tenant Without a Lease link',
    firstLevelLink: 'Personal',
    secondLevelLink: 'Landlords',
    thirdLevelLink: 'Tenant Without a Lease',
    expectedUrl: 'legalshield.com/landlords/tenant-without-a-lease/',
    disabled: false,
  },
  {
    testCaseName: 'Verify the Personal/Landlords/Eviction Defenses link',
    firstLevelLink: 'Personal',
    secondLevelLink: 'Landlords',
    thirdLevelLink: 'Eviction Defenses',
    expectedUrl: 'legalshield.com/landlords/eviction-defenses/',
    disabled: false,
  },
  {
    testCaseName: 'Verify the Personal/Landlords/Problem Tenants link',
    firstLevelLink: 'Personal',
    secondLevelLink: 'Landlords',
    thirdLevelLink: 'Problem Tenants',
    expectedUrl: 'legalshield.com/landlords/problem-tenant/',
    disabled: false,
  },
  {
    testCaseName: 'Verify the Personal/Landlords/Security Deposits link',
    firstLevelLink: 'Personal',
    secondLevelLink: 'Landlords',
    thirdLevelLink: 'Security Deposits',
    expectedUrl: 'legalshield.com/landlords/security-deposit/',
    disabled: false,
  },
  {
    testCaseName: 'Verify the Personal/Family Law/Family Law Matters link',
    firstLevelLink: 'Personal',
    secondLevelLink: 'Family Law',
    thirdLevelLink: 'Family Law Matters',
    expectedUrl: 'legalshield.com/family-law/',
    disabled: false,
  },
  {
    testCaseName: 'Verify the Personal/Family Law/Divorce link',
    firstLevelLink: 'Personal',
    secondLevelLink: 'Family Law',
    thirdLevelLink: 'Divorce',
    expectedUrl: 'legalshield.com/family-law/divorce/',
    disabled: false,
  },
  {
    testCaseName: 'Verify the Personal/Family Law/Prenuptial Agreements link',
    firstLevelLink: 'Personal',
    secondLevelLink: 'Family Law',
    thirdLevelLink: 'Prenuptial Agreements',
    expectedUrl: 'legalshield.com/family-law/prenuptial-agreement/',
    disabled: false,
  },
  {
    testCaseName: 'Verify the Personal/Family Law/Child Guardianship Custody & Visitation link',
    firstLevelLink: 'Personal',
    secondLevelLink: 'Family Law',
    thirdLevelLink: 'Child Guardianship Custody & Visitation',
    expectedUrl: 'legalshield.com/family-law/child-custody/',
    disabled: false,
  },
  {
    testCaseName: 'Verify the Personal/Family Law/Name Changes link',
    firstLevelLink: 'Personal',
    secondLevelLink: 'Family Law',
    thirdLevelLink: 'Name Changes',
    expectedUrl: 'legalshield.com/family-law/name-change/',
    disabled: false,
  },
  {
    testCaseName: 'Verify the Personal/Family Law/Probate link',
    firstLevelLink: 'Personal',
    secondLevelLink: 'Family Law',
    thirdLevelLink: 'Probate',
    expectedUrl: 'legalshield.com/estate-planning/probate/',
    disabled: false,
  },
  {
    testCaseName: 'Verify the Personal/Employee Rights/Employee Right Matters link',
    firstLevelLink: 'Personal',
    secondLevelLink: 'Employee Rights',
    thirdLevelLink: 'Employee Right Matters',
    expectedUrl: 'legalshield.com/employment-law/',
    disabled: false,
  },
  {
    testCaseName: 'Verify the Personal/Traffic & Accidents/Traffic & Accident Matters link',
    firstLevelLink: 'Personal',
    secondLevelLink: 'Traffic & Accidents',
    thirdLevelLink: 'Traffic & Accident Matters',
    expectedUrl: 'legalshield.com/traffic-accident',
    disabled: false,
  },
  {
    testCaseName: 'Verify the Personal/Add on Coverage/Trial Defense Supplement link',
    firstLevelLink: 'Personal',
    secondLevelLink: 'Add on Coverage',
    thirdLevelLink: 'Trial Defense Supplement',
    expectedUrl: 'legalshield.com/extended-trial-and-lawsuit-defense-protection',
    disabled: false,
  },
  {
    testCaseName: 'Verify the Personal/Add on Coverage/Gun Owners Supplement link',
    firstLevelLink: 'Personal',
    secondLevelLink: 'Add on Coverage',
    thirdLevelLink: 'Gun Owners Supplement',
    expectedUrl: 'legalshield.com/gun-supplement/',
    disabled: false,
  },
  {
    testCaseName: 'Verify the Personal/Add on Coverage/Home Business Supplement link',
    firstLevelLink: 'Personal',
    secondLevelLink: 'Add on Coverage',
    thirdLevelLink: 'Home Business Supplement',
    expectedUrl: 'legalshield.com/legal-protection-home-business/',
    disabled: false,
  },
  {
    testCaseName: 'Verify the Personal/Add on Coverage/Rideshare Supplement link',
    firstLevelLink: 'Personal',
    secondLevelLink: 'Add on Coverage',
    thirdLevelLink: 'Rideshare Supplement',
    expectedUrl: 'legalshield.com/legal-help-ride-share-and-delivery-drivers/',
    disabled: false,
  },
  {
    testCaseName: 'Verify the Business/Debt Collection/Bankruptcy & Debt Collection Matters link',
    firstLevelLink: 'Business',
    secondLevelLink: 'Debt Collection',
    thirdLevelLink: 'Bankruptcy & Debt Collection Matters',
    expectedUrl: 'legalshield.com/collection/',
    disabled: false,
  },
  {
    testCaseName: 'Verify the Business/Debt Collection/Small Claims Court link',
    firstLevelLink: 'Business',
    secondLevelLink: 'Debt Collection',
    thirdLevelLink: 'Small Claims Court',
    expectedUrl: 'legalshield.com/collection/small-claims-court/',
    disabled: false,
  },
  {
    testCaseName: 'Verify the Business/Debt Collection/Debt Collection Letter link',
    firstLevelLink: 'Business',
    secondLevelLink: 'Debt Collection',
    thirdLevelLink: 'Debt Collection Letter',
    expectedUrl: 'legalshield.com/collection/collection-letter/',
    disabled: false,
  },
  {
    testCaseName: 'Verify the Business/Debt Collection/Collection Lawyer link',
    firstLevelLink: 'Business',
    secondLevelLink: 'Debt Collection',
    thirdLevelLink: 'Collection Lawyer',
    expectedUrl: 'legalshield.com/collection/collection-attorney/',
    disabled: false,
  },
  {
    testCaseName: 'Verify the Business/Debt Collection/Debt Negotiation link',
    firstLevelLink: 'Business',
    secondLevelLink: 'Debt Collection',
    thirdLevelLink: 'Debt Negotiation',
    expectedUrl: 'legalshield.com/collection/negotiation/',
    disabled: false,
  },
  {
    testCaseName: 'Verify the Business/Debt Collection/Debt Settlement link',
    firstLevelLink: 'Business',
    secondLevelLink: 'Debt Collection',
    thirdLevelLink: 'Debt Settlement',
    expectedUrl: 'legalshield.com/collection/settlement/',
    disabled: false,
  },
  {
    testCaseName: 'Verify the Business/Business Licenses/Business License Matters link',
    firstLevelLink: 'Business',
    secondLevelLink: 'Business Licenses',
    thirdLevelLink: 'Business License Matters',
    expectedUrl: 'legalshield.com/business-licenses/',
    disabled: false,
  },
  {
    testCaseName: 'Verify the Business/Business Licenses/Business Permits link',
    firstLevelLink: 'Business',
    secondLevelLink: 'Business Licenses',
    thirdLevelLink: 'Business Permits',
    expectedUrl: 'legalshield.com/business-licenses/business-permits/',
    disabled: false,
  },
  {
    testCaseName: 'Verify the Business/Business Licenses/Federal & State Requirements link',
    firstLevelLink: 'Business',
    secondLevelLink: 'Business Licenses',
    thirdLevelLink: 'Federal & State Requirements',
    expectedUrl: 'legalshield.com/business-licenses/federal-and-state-requirements/',
    disabled: false,
  },
  {
    testCaseName: 'Verify the Business/Business Licenses/DBA link',
    firstLevelLink: 'Business',
    secondLevelLink: 'Business Licenses',
    thirdLevelLink: 'DBA',
    expectedUrl: 'legalshield.com/business-licenses/dba/',
    disabled: false,
  },
  {
    testCaseName: 'Verify the Business/Civil Litigation/Civil Litigation Matters link',
    firstLevelLink: 'Business',
    secondLevelLink: 'Civil Litigation',
    thirdLevelLink: 'Civil Litigation Matters',
    expectedUrl: 'legalshield.com/civil-litigation/',
    disabled: false,
  },
  {
    testCaseName: 'Verify the Business/Civil Litigation/Labor Lawsuits link',
    firstLevelLink: 'Business',
    secondLevelLink: 'Civil Litigation',
    thirdLevelLink: 'Labor Lawsuits',
    expectedUrl: 'legalshield.com/civil-litigation/labor-lawsuit/',
    expectedTitle: 'Find a Labor Lawyer Near You & Get Legal Advice - LegalShield',
    disabled: false,
  },
  {
    testCaseName: 'Verify the Business/Civil Litigation/Intellectual Property Infringement link',
    firstLevelLink: 'Business',
    secondLevelLink: 'Civil Litigation',
    thirdLevelLink: 'Intellectual Property Infringement',
    expectedUrl: 'legalshield.com/civil-litigation/intellectual-property-infringement/',
    disabled: false,
  },
  {
    testCaseName: 'Verify the Business/Civil Litigation/Employment Litigation link',
    firstLevelLink: 'Business',
    secondLevelLink: 'Civil Litigation',
    thirdLevelLink: 'Employment Litigation',
    expectedUrl: 'legalshield.com/civil-litigation/employment-litigation/',
    disabled: false,
  },
  {
    testCaseName: 'Verify the Business/Civil Litigation/Breach of Contract link',
    firstLevelLink: 'Business',
    secondLevelLink: 'Civil Litigation',
    thirdLevelLink: 'Breach of Contract',
    expectedUrl: 'legalshield.com/civil-litigation/breach-of-contract/',
    disabled: false,
  },
  {
    testCaseName: 'Verify the Business/Civil Litigation/Bankruptcy and Dissolution link',
    firstLevelLink: 'Business',
    secondLevelLink: 'Civil Litigation',
    thirdLevelLink: 'Bankruptcy and Dissolution',
    expectedUrl: 'legalshield.com/civil-litigation/bankruptcy-dissolution/',
    disabled: false,
  },
  {
    testCaseName: 'Verify the Business/Contracts & Agreements/Contracts & Agreement Matters link',
    firstLevelLink: 'Business',
    secondLevelLink: 'Contracts & Agreements',
    thirdLevelLink: 'Contracts & Agreement Matters',
    expectedUrl: 'legalshield.com/contracts/',
    disabled: false,
  },
  {
    testCaseName: 'Verify the Business/Contracts & Agreements/Demand for Payment link',
    firstLevelLink: 'Business',
    secondLevelLink: 'Contracts & Agreements',
    thirdLevelLink: 'Demand for Payment',
    expectedUrl: 'legalshield.com/contracts/demand-for-payment/',
    disabled: false,
  },
  {
    testCaseName: 'Verify the Business/Contracts & Agreements/Lease Agreements link',
    firstLevelLink: 'Business',
    secondLevelLink: 'Contracts & Agreements',
    thirdLevelLink: 'Lease Agreements',
    expectedUrl: 'legalshield.com/contracts/lease-agreements/',
    disabled: false,
  },
  {
    testCaseName: 'Verify the Business/Contracts & Agreements/Independent Contractor Agreements link',
    firstLevelLink: 'Business',
    secondLevelLink: 'Contracts & Agreements',
    thirdLevelLink: 'Independent Contractor Agreements',
    expectedUrl: 'legalshield.com/contracts/independent-contractor-agreement/',
    disabled: false,
  },
  {
    testCaseName: 'Verify the Business/Contracts & Agreements/Eviction Notices link',
    firstLevelLink: 'Business',
    secondLevelLink: 'Contracts & Agreements',
    thirdLevelLink: 'Eviction Notices',
    expectedUrl: 'legalshield.com/contracts/eviction-notices/',
    disabled: false,
  },
  {
    testCaseName: 'Verify the Business/Employers/Employer Matters link',
    firstLevelLink: 'Business',
    secondLevelLink: 'Employers',
    thirdLevelLink: 'Employer Matters',
    expectedUrl: 'legalshield.com/employment/',
    disabled: false,
  },
  {
    testCaseName: 'Verify the Business/Employers/Hiring and Firing link',
    firstLevelLink: 'Business',
    secondLevelLink: 'Employers',
    thirdLevelLink: 'Hiring and Firing',
    expectedUrl: 'legalshield.com/employment/hiring-and-firing/',
    disabled: false,
  },
  {
    testCaseName: 'Verify the Business/Employers/ADA link',
    firstLevelLink: 'Business',
    secondLevelLink: 'Employers',
    thirdLevelLink: 'ADA',
    expectedUrl: 'legalshield.com/employment/ada/',
    disabled: false,
  },
  {
    testCaseName: 'Verify the Business/Employers/Workers’ Comp link',
    firstLevelLink: 'Business',
    secondLevelLink: 'Employers',
    thirdLevelLink: 'Workers’ Comp',
    expectedUrl: 'legalshield.com/employment/workers-comp/',
    disabled: false,
  },
  {
    testCaseName: 'Verify the Business/Employers/Employment Litigation link',
    firstLevelLink: 'Business',
    secondLevelLink: 'Employers',
    thirdLevelLink: 'Employment Litigation',
    expectedUrl: 'legalshield.com/civil-litigation/employment-litigation/',
    disabled: false,
  },
  {
    testCaseName: 'Verify the Business/Employers/Labor Lawsuits link',
    firstLevelLink: 'Business',
    secondLevelLink: 'Employers',
    thirdLevelLink: 'Labor Lawsuits',
    expectedUrl: 'legalshield.com/civil-litigation/labor-lawsuit/',
    disabled: false,
  },
  {
    testCaseName: 'Verify the Business/Intellectual Property/Intellectual Property Matters Link',
    firstLevelLink: 'Business',
    secondLevelLink: 'Intellectual Property',
    thirdLevelLink: 'Intellectual Property Matters',
    expectedUrl: 'legalshield.com/intellectual-property/',
    disabled: false,
  },
  {
    testCaseName: 'Verify the Business/Intellectual Property/Copyright link',
    firstLevelLink: 'Business',
    secondLevelLink: 'Intellectual Property',
    thirdLevelLink: 'Copyright',
    expectedUrl: 'legalshield.com/intellectual-property/copyright/',
    disabled: false,
  },
  {
    testCaseName: 'Verify the Business/Intellectual Property/Trademarks link',
    firstLevelLink: 'Business',
    secondLevelLink: 'Intellectual Property',
    thirdLevelLink: 'Trademarks',
    expectedUrl: 'legalshield.com/intellectual-property/trademark/',
    disabled: false,
  },
  {
    testCaseName: 'Verify the Business/Landlords/Landlord Matters link',
    firstLevelLink: 'Business',
    secondLevelLink: 'Landlords',
    thirdLevelLink: 'Landlord Matters',
    expectedUrl: 'legalshield.com/landlords/',
    disabled: false,
  },
  {
    testCaseName: 'Verify the Business/Landlords/Leases link',
    firstLevelLink: 'Business',
    secondLevelLink: 'Landlords',
    thirdLevelLink: 'Leases',
    expectedUrl: 'legalshield.com/landlords/negotiating-leases/',
    disabled: false,
  },
  {
    testCaseName: 'Verify the Business/Landlords/Problem Tenants link',
    firstLevelLink: 'Business',
    secondLevelLink: 'Landlords',
    thirdLevelLink: 'Problem Tenants',
    expectedUrl: 'legalshield.com/landlords/problem-tenant/',
    disabled: false,
  },
  {
    testCaseName: 'Verify the Business/Landlords/Security Deposits link',
    firstLevelLink: 'Business',
    secondLevelLink: 'Landlords',
    thirdLevelLink: 'Security Deposits',
    expectedUrl: 'legalshield.com/landlords/security-deposit/',
    disabled: false,
  },
  {
    testCaseName: 'Verify the Business/Add on Coverage/Business Plus Supplement link',
    firstLevelLink: 'Business',
    secondLevelLink: 'Add on Coverage',
    thirdLevelLink: 'Business Plus Supplement',
    expectedUrl: 'legalshield.com/business-plus-supplement/',
    disabled: false,
  },
  {
    testCaseName: 'Verify the Business/Add on Coverage/Trial Defense Supplement link',
    firstLevelLink: 'Business',
    secondLevelLink: 'Add on Coverage',
    thirdLevelLink: 'Trial Defense Supplement',
    expectedUrl: 'legalshield.com/trial-defense-for-business-supplement/',
    disabled: false,
  },
];

export const headerTwoLinksData = [
  {
    testCaseName: 'Verify the Resources/How it Works link',
    firstLevelLink: 'Resources',
    secondLevelLink: 'How it Works',
    expectedUrl: 'legalshield.com/why-legalshield/how-it-works/',
    disabled: false,
  },
  {
    testCaseName: 'Verify the Resources/Blog link',
    firstLevelLink: 'Resources',
    secondLevelLink: 'Blog',
    expectedUrl: 'legalshield.com/blog/',
    disabled: false,
  },
  {
    testCaseName: 'Verify the Resources/Lawyer Directory link',
    firstLevelLink: 'Resources',
    secondLevelLink: 'Lawyer Directory',
    expectedUrl: 'legalshield.com/law-firms/',
    disabled: false,
  },
  {
    testCaseName: 'Verify the Resources/FAQ link',
    firstLevelLink: 'Resources',
    secondLevelLink: 'FAQ',
    expectedUrl: 'legalshield.com/faq/',
    disabled: false,
  },
  {
    testCaseName: 'Verify the Resources/About Us link',
    firstLevelLink: 'Resources',
    secondLevelLink: 'About Us',
    expectedUrl: 'legalshield.com/why-legalshield/about/',
    disabled: false,
  },
  {
    testCaseName: 'Verify the Resources/Contact Us link',
    firstLevelLink: 'Resources',
    secondLevelLink: 'Contact Us',
    expectedUrl: 'legalshield.com/contact/',
    disabled: false,
  },
];
