export const navigationLinks = [
  {
    testCaseName: 'User can navigate to the How It Works page',
    parentLink: '',
    href: '/why-legalshield/how-it-works',
    tags: '',
    disabled: false,
  },
  {
    testCaseName: 'User can navigate to the Legal Plans Overview page',
    parentLink: '',
    href: '/legal-plans-overview',
    tags: '',
    disabled: false,
  },
  {
    testCaseName: 'User can navigate to the Estate Planning page',
    parentLink: 'Common Problems',
    href: '/estate-planning',
    tags: '',
    disabled: false,
  },
  {
    testCaseName: 'User can navigate to the Consumer Finance page',
    parentLink: 'Common Problems',
    href: '/consumer-finance',
    tags: '',
    disabled: false,
  },
  {
    testCaseName: 'User can navigate to the Debt Collection page',
    parentLink: 'Common Problems',
    href: '/collection',
    tags: '',
    disabled: false,
  },
  {
    testCaseName: 'User can navigate to the Business Licenses page',
    parentLink: 'Common Problems',
    href: '/business-licenses',
    tags: '',
    disabled: false,
  },
  {
    testCaseName: 'User can navigate to the Renters page',
    parentLink: 'Common Problems',
    href: '/renters',
    tags: '',
    disabled: false,
  },
  {
    testCaseName: 'User can navigate to the Real Estate page',
    parentLink: 'Common Problems',
    href: '/real-estate',
    tags: '',
    disabled: false,
  },
  {
    testCaseName: 'User can navigate to the Civil Litigation page',
    parentLink: 'Common Problems',
    href: '/civil-litigation',
    tags: '',
    disabled: false,
  },
  {
    testCaseName: 'User can navigate to the Contracts page',
    parentLink: 'Common Problems',
    href: '/contracts',
    tags: '',
    disabled: false,
  },
  {
    testCaseName: 'User can navigate to the Landlords page',
    parentLink: 'Common Problems',
    href: '/landlords',
    tags: '',
    disabled: false,
  },
  {
    testCaseName: 'User can navigate to the Family Law page',
    parentLink: 'Common Problems',
    href: '/family-law',
    tags: '',
    disabled: false,
  },
  {
    testCaseName: 'User can navigate to the Employment page',
    parentLink: 'Common Problems',
    href: '/employment',
    tags: '',
    disabled: false,
  },
  {
    testCaseName: 'User can navigate to the Intellectual Property page',
    parentLink: 'Common Problems',
    href: '/intellectual-property',
    tags: '',
    disabled: false,
  },
  {
    testCaseName: 'User can navigate to the Employee Rights page',
    parentLink: 'Common Problems',
    href: '/employment-law',
    tags: '',
    disabled: false,
  },
  {
    testCaseName: 'User can navigate to the Traffic and Accidents page',
    parentLink: 'Common Problems',
    href: '/traffic-accident',
    tags: '',
    disabled: false,
  },
  {
    testCaseName: 'User can navigate to the Commercial Drivers page',
    parentLink: 'Common Problems',
    href: '/legal-protection-truck-drivers-and-other-commercial-drivers',
    tags: '',
    disabled: false,
  },
  {
    testCaseName: 'User can navigate to the Add on Coverage (Your Life) page',
    parentLink: 'Common Problems',
    href: '/personal-plan/supplements',
    tags: '',
    disabled: false,
  },
  {
    testCaseName: 'User can navigate to the Add on Coverage (Your Business) page',
    parentLink: 'Common Problems',
    href: '/small-business-add-on-coverage',
    tags: '',
    disabled: false,
  },
  {
    testCaseName: 'User can navigate to the Blog page',
    parentLink: 'Resources',
    href: '/resources/blog',
    tags: '',
    disabled: false,
  },
  {
    testCaseName: 'User can navigate to the FAQ page',
    parentLink: 'Resources',
    href: '/faq',
    tags: '',
    disabled: false,
  },
  {
    testCaseName: 'User can navigate to the News & Press page',
    parentLink: 'Resources',
    href: '/resources/news',
    tags: '',
    disabled: false,
  },
  {
    testCaseName: 'User can navigate to the Consumer Stress Legal Index page',
    parentLink: 'Resources',
    href: '/resources/consumer-stress-legal-index',
    tags: '',
    disabled: false,
  },
  {
    testCaseName: 'User can navigate to the Contact Us page',
    parentLink: 'Resources',
    href: '/contact',
    tags: '',
    disabled: false,
  },
  {
    testCaseName: 'User can navigate to the Lawyer Directory page',
    parentLink: 'Resources',
    href: '/law-firms',
    tags: '',
    disabled: false,
  },
  {
    testCaseName: 'User can navigate to the Employee Benefits page',
    parentLink: 'Resources',
    href: '/resources/employee-benefits',
    tags: '',
    disabled: false,
  },
  {
    testCaseName: 'User can navigate to the Primary vs Contingent Beneficiary page',
    parentLink: 'Resources',
    href: '/blog/primary-vs-contingent-beneficiary',
    tags: '',
    disabled: true, //disabled until QAOPS-1260 complete
  },
  {
    testCaseName: 'User can navigate to the Small Business Owners Guide page',
    parentLink: 'Resources',
    href: '/blog/small-business-owners-guide-debt-collection',
    tags: '',
    disabled: true,//disabled until QAOPS-1260 complete
  },
];
