export const navigationLinks = [
  {
    'testCaseName': 'Navigate to Estate Planning Page',
    'parentLink': 'Common Problems',
    'childLink': 'Estate Planning',
    'expectedUrl': 'legalshield.com/estate-planning',
    'tags': '',
    'disabled': false,
  },
  {
    'testCaseName': 'Navigate to Consumer Finance Page',
    'parentLink': 'Common Problems',
    'childLink': 'Consumer Finance',
    'expectedUrl': 'legalshield.com/consumer-finance',
    'tags': '',
    'disabled': false,
  },
  {
    'testCaseName': 'Navigate to Debt Collection Page',
    'parentLink': 'Common Problems',
    'childLink': 'Debt Collection',
    'expectedUrl': 'legalshield.com/collection',
    'tags': '',
    'disabled': false,
  },
  {
    'testCaseName': 'Navigate to Business Licenses Page',
    'parentLink': 'Common Problems',
    'childLink': 'Business Licenses',
    'expectedUrl': 'legalshield.com/business-licenses',
    'tags': '',
    'disabled': false,
  },
  {
    'testCaseName': 'Navigate to Renters Page',
    'parentLink': 'Common Problems',
    'childLink': 'Renters',
    'expectedUrl': 'legalshield.com/renters',
    'tags': '',
    'disabled': false,
  },
  {
    'testCaseName': 'Navigate to Real Estate Page',
    'parentLink': 'Common Problems',
    'childLink': 'Real Estate',
    'expectedUrl': 'legalshield.com/real-estate',
    'tags': '',
    'disabled': false,
  },
  {
    'testCaseName': 'Navigate to Civil Litigation Page',
    'parentLink': 'Common Problems',
    'childLink': 'Civil Litigation',
    'expectedUrl': 'legalshield.com/civil-litigation',
    'tags': '',
    'disabled': false,
  },
  {
    'testCaseName': 'Navigate to Contracts & Agreements Page',
    'parentLink': 'Common Problems',
    'childLink': 'Contracts',
    'expectedUrl': 'legalshield.com/contracts',
    'tags': '@WIP',
    'disabled': false,
  },
  {
    'testCaseName': 'Navigate to Landlords Page',
    'parentLink': 'Common Problems',
    'childLink': 'Landlords',
    'expectedUrl': 'legalshield.com/landlords',
    'tags': '',
    'disabled': false,
  },
  {
    'testCaseName': 'Navigate to Family Law Page',
    'parentLink': 'Common Problems',
    'childLink': 'Family Law',
    'expectedUrl': 'legalshield.com/family-law',
    'tags': '',
    'disabled': false,
  },
  {
    'testCaseName': 'Navigate to Employment Page',
    'parentLink': 'Common Problems',
    'childLink': 'Employment',
    'expectedUrl': 'legalshield.com/employment',
    'tags': '',
    'disabled': false,
  },
  {
    'testCaseName': 'Navigate to Intellectual Property Page',
    'parentLink': 'Common Problems',
    'childLink': 'Intellectual Property',
    'expectedUrl': 'legalshield.com/intellectual-property',
    'tags': '',
    'disabled': false,
  },
  {
    'testCaseName': 'Navigate to Employee Rights Page',
    'parentLink': 'Common Problems',
    'childLink': 'Employee Rights',
    'expectedUrl': 'legalshield.com/employment-law',
    'tags': '',
    'disabled': false,
  },
  {
    'testCaseName': 'Navigate to Traffic and Accidents Page',
    'parentLink': 'Common Problems',
    'childLink': 'Traffic and Accidents',
    'expectedUrl': 'legalshield.com/traffic-accident',
    'tags': '',
    'disabled': false,
  },
  {
    'testCaseName': 'Navigate to Commercial Drivers Page',
    'parentLink': 'Common Problems',
    'childLink': 'Commercial Drivers',
    'expectedUrl': 'legalshield.com/legal-protection-truck-drivers-and-other-commercial-drivers',
    'tags': '@wip',
    'disabled': false,
  },
  {
    'testCaseName': 'Navigate to Add on Coverage (Your Life) Page',
    'parentLink': 'Common Problems',
    'childLink': 'Add on Coverage (Your Life)',
    'expectedUrl': 'legalshield.com/personal-plan/supplements',
    'tags': '',
    'disabled': false,
  },
  {
    'testCaseName': 'Navigate to Add on Coverage (Your Business) Page',
    'parentLink': 'Common Problems',
    'childLink': 'Add on Coverage (Your Business)',
    'expectedUrl': 'legalshield.com/small-business-add-on-coverage',
    'tags': '',
    'disabled': false,
  },
  {
    'testCaseName': 'Navigate to Blog Page',
    'parentLink': 'Resources',
    'childLink': 'Blog',
    'expectedUrl': 'legalshield.com/resources/blog',
    'tags': '',
    'disabled': false,
  },
  {
    'testCaseName': 'Navigate to FAQ Page',
    'parentLink': 'Resources',
    'childLink': 'FAQ',
    'expectedUrl': 'legalshield.com/faq',
    'tags': '',
    'disabled': false,
  },
  {
    'testCaseName': 'Navigate to News & Press Page',
    'parentLink': 'Resources',
    'childLink': 'News & Press',
    'expectedUrl': 'legalshield.com/resources/news',
    'tags': '',
    'disabled': false,
  },
  {
    'testCaseName': 'Navigate to Consumer Stress Legal Index Page',
    'parentLink': 'Resources',
    'childLink': 'Consumer Stress Legal Index',
    'expectedUrl': 'legalshield.com/resources/consumer-stress-legal-index',
    'tags': '',
    'disabled': false,
  },
  {
    'testCaseName': 'Navigate to Contact US Page',
    'parentLink': 'Resources',
    'childLink': 'Contact US',
    'expectedUrl': 'legalshield.com/contact',
    'tags': '',
    'disabled': false,
  },
  {
    'testCaseName': 'Navigate to Lawyer Directory Page',
    'parentLink': 'Resources',
    'childLink': 'Lawyer Directory',
    'expectedUrl': 'legalshield.com/law-firms',
    'tags': '',
    'disabled': false,
  },
  {
    'testCaseName': 'Navigate to Employee Benefits Page',
    'parentLink': 'Resources',
    'childLink': 'Employee Benefits',
    'expectedUrl': 'legalshield.com/resources/employee-benefits',
    'tags': '',
    'disabled': false,
  },
  {
    'testCaseName': 'Navigate to Primary vs Contingent Beneficiary Page',
    'parentLink': 'Resources',
    'childLink': 'Primary vs Contingent Beneficiary',
    'expectedUrl': 'legalshield.com/blog/primary-vs-contingent-beneficiary',
    'tags': '',
    'disabled': false,
  },
  {
    'testCaseName': 'Navigate to Estate Planning Guide Page',
    'parentLink': 'Resources',
    'childLink': 'Estate Planning Guide',
    'expectedUrl': 'legalshield.com/blog/estate-planning-guide',
    'tags': '',
    'disabled': false,
  }
];
