/* eslint-disable sort-keys-fix/sort-keys-fix */
/* eslint-disable sort-keys */

export const legalshieldServiceGbbData = [
  { disabled: false, stateName: 'Alabama', stateAbbreviation: 'AL', expectedGbb: false, tag: '@gbboff' },
  { disabled: false, stateName: 'Alaska', stateAbbreviation: 'AK', expectedGbb: false, tag: '@gbboff' },
  { disabled: false, stateName: 'Arizona', stateAbbreviation: 'AZ', expectedGbb: true, tag: '@gbbon' },
  { disabled: false, stateName: 'Arkansas', stateAbbreviation: 'AR', expectedGbb: false, tag: '@gbboff' },
  { disabled: false, stateName: 'California', stateAbbreviation: 'CA', expectedGbb: true, tag: '@gbbon' },
  { disabled: false, stateName: 'Colorado', stateAbbreviation: 'CO', expectedGbb: true, tag: '@gbbon' },
  { disabled: false, stateName: 'Connecticut', stateAbbreviation: 'CT', expectedGbb: true, tag: '@gbbon' },
  { disabled: false, stateName: 'Delaware', stateAbbreviation: 'DE', expectedGbb: false, tag: '@gbboff' },
  { disabled: false, stateName: 'District of Columbia', stateAbbreviation: 'DC', expectedGbb: false, tag: '@gbboff' },
  { disabled: false, stateName: 'Florida', stateAbbreviation: 'FL', expectedGbb: true, tag: '@gbbon' },
  { disabled: false, stateName: 'Georgia', stateAbbreviation: 'GA', expectedGbb: true, tag: '@gbbon' },
  { disabled: false, stateName: 'Hawaii', stateAbbreviation: 'HI', expectedGbb: false, tag: '@gbboff' },
  { disabled: false, stateName: 'Idaho', stateAbbreviation: 'ID', expectedGbb: false, tag: '@gbboff' },
  { disabled: false, stateName: 'Illinois', stateAbbreviation: 'IL', expectedGbb: true, tag: '@gbbon' },
  { disabled: false, stateName: 'Indiana', stateAbbreviation: 'IN', expectedGbb: false, tag: '@gbboff' },
  { disabled: false, stateName: 'Iowa', stateAbbreviation: 'IA', expectedGbb: false, tag: '@gbboff' },
  { disabled: false, stateName: 'Kansas', stateAbbreviation: 'KS', expectedGbb: true, tag: '@gbbon' },
  { disabled: false, stateName: 'Kentucky', stateAbbreviation: 'KY', expectedGbb: false, tag: '@gbboff' },
  { disabled: false, stateName: 'Louisiana', stateAbbreviation: 'LA', expectedGbb: false, tag: '@gbboff' },
  { disabled: false, stateName: 'Maine', stateAbbreviation: 'ME', expectedGbb: false, tag: '@gbboff' },
  { disabled: false, stateName: 'Maryland', stateAbbreviation: 'MD', expectedGbb: true, tag: '@gbbon' },
  { disabled: false, stateName: 'Massachusetts', stateAbbreviation: 'MA', expectedGbb: false, tag: '@gbboff' },
  { disabled: false, stateName: 'Michigan', stateAbbreviation: 'MI', expectedGbb: true, tag: '@gbbon' },
  { disabled: false, stateName: 'Minnesota', stateAbbreviation: 'MN', expectedGbb: false, tag: '@gbboff' },
  { disabled: false, stateName: 'Mississippi', stateAbbreviation: 'MS', expectedGbb: false, tag: '@gbboff' },
  { disabled: false, stateName: 'Missouri', stateAbbreviation: 'MO', expectedGbb: false, tag: '@gbboff' },
  { disabled: false, stateName: 'Montana', stateAbbreviation: 'MT', expectedGbb: false, tag: '@gbboff' },
  { disabled: false, stateName: 'Nebraska', stateAbbreviation: 'NE', expectedGbb: false, tag: '@gbboff' },
  { disabled: false, stateName: 'Nevada', stateAbbreviation: 'NV', expectedGbb: false, tag: '@gbboff' },
  { disabled: false, stateName: 'New Hampshire', stateAbbreviation: 'NH', expectedGbb: false, tag: '@gbboff' },
  { disabled: false, stateName: 'New Jersey', stateAbbreviation: 'NJ', expectedGbb: false, tag: '@gbboff' },
  { disabled: false, stateName: 'New Mexico', stateAbbreviation: 'NM', expectedGbb: false, tag: '@gbboff' },
  { disabled: false, stateName: 'New York', stateAbbreviation: 'NY', expectedGbb: false, tag: '@gbboff' },
  { disabled: false, stateName: 'North Carolina', stateAbbreviation: 'NC', expectedGbb: false, tag: '@gbboff' },
  { disabled: false, stateName: 'North Dakota', stateAbbreviation: 'ND', expectedGbb: false, tag: '@gbboff' },
  { disabled: false, stateName: 'Ohio', stateAbbreviation: 'OH', expectedGbb: true, tag: '@gbbon' },
  { disabled: false, stateName: 'Oklahoma', stateAbbreviation: 'OK', expectedGbb: true, tag: '@gbbon' },
  { disabled: false, stateName: 'Oregon', stateAbbreviation: 'OR', expectedGbb: false, tag: '@gbboff' },
  { disabled: false, stateName: 'Pennsylvania', stateAbbreviation: 'PA', expectedGbb: true, tag: '@gbbon' },
  { disabled: false, stateName: 'Rhode Island', stateAbbreviation: 'RI', expectedGbb: false, tag: '@gbboff' },
  { disabled: false, stateName: 'South Carolina', stateAbbreviation: 'SC', expectedGbb: false, tag: '@gbboff' },
  { disabled: false, stateName: 'South Dakota', stateAbbreviation: 'SD', expectedGbb: false, tag: '@gbboff' },
  { disabled: false, stateName: 'Tennessee', stateAbbreviation: 'TN', expectedGbb: true, tag: '@gbbon' },
  { disabled: false, stateName: 'Texas', stateAbbreviation: 'TX', expectedGbb: true, tag: '@gbbon' },
  { disabled: false, stateName: 'Utah', stateAbbreviation: 'UT', expectedGbb: false, tag: '@gbboff' },
  { disabled: false, stateName: 'Vermont', stateAbbreviation: 'VT', expectedGbb: false, tag: '@gbboff' },
  { disabled: false, stateName: 'Virginia', stateAbbreviation: 'VA', expectedGbb: false, tag: '@gbboff' },
  { disabled: false, stateName: 'Washington', stateAbbreviation: 'WA', expectedGbb: true, tag: '@gbbon' },
  { disabled: false, stateName: 'West Virginia', stateAbbreviation: 'WV', expectedGbb: false, tag: '@gbboff' },
  { disabled: false, stateName: 'Wisconsin', stateAbbreviation: 'WI', expectedGbb: false, tag: '@gbboff' },
  { disabled: false, stateName: 'Wyoming', stateAbbreviation: 'WY', expectedGbb: false, tag: '@gbboff' },
];
