export default class DataUtils {
  static readonly data = {
    testingHarness: {
      ca: {
        bd: {
          Account: '0000000',
          Institution: '260',
          Transit: '11242',
          name: 'Tester',
          postalCode: '20147',
          province: {
            BC: 'British Columbia',
          },
        },
        cc: {
          cn: '4444333322221111',
          cvv: '111',
          exp: '1 / 23',
          name: 'Tester',
          postalCode: '20147',
        },
      },
      lineOfBusiness: {
        IDShield: '3',
        IDShieldCanada: '0',
        LegalShield: '2',
        LegalShieldCanada: '1',
        ProfilesOfSuccess: '1',
        networkShieldAssociate: '0',
      },
      plans: {
        ca: {
          IDShieldFamily: 'IDSCF2',
          IDShieldIndividual: 'IDSCI2',
          LegalPlan: 'CA22',
          LegalPlanBusinessPlusSupplement: 'BPS',
          LegalPlanHomeBusinessSupplement: 'HB3',
          LegalPlanRideShareandDeliverySupplement: 'RS2',
          LegalPlanTrialDefenceSupplement: 'TD3',
          SmallBusinessLegalEssentials: 'ESS',
          SmallBusinessLegalEssentialsBusinessPlusSupplement: 'BPS',
          SmallBusinessLegalPlus: 'PLUS',
          SmallBusinessLegalPlusBusinessPlusSupplement: 'BPS',
          SmallBusinessLegalPlusTrialDefenceforBusiness: 'TDB',
          SmallBusinessLegalPro: 'PRO',
          SmallBusinessLegalProBusinessPlusSupplement: 'BPS',
          SmallBusinessLegalProTrialDefenceforBusiness: 'TDB',
        },
        us: {
          CommercialDriversLegalPlan: 'CDLP',
          IDShieldFamily: 'IDSF',
          IDShieldForBusinessEssentials: 'IDSBUS',
          IDShieldForBusinessPlus: 'IDSBUS2',
          IDShieldIndividual: 'IDSI',
          IDShieldThreeBureauFamily: 'IDSF3',
          IDShieldThreeBureauIndividual: 'IDSI3',
          LaunchLLCFormation: 'LNCHLGL',
          LegalPlan: 'LPUS21',
          LegalPlanBusinessPlusSupplement: 'BPS',
          LegalPlanGunOwnersSupplement: 'GO2',
          LegalPlanHomeBusinessSupplement: 'HB3',
          LegalPlanRideShareandDeliverySupplement: 'RS2',
          LegalPlanTrialDefenceSupplement: 'TD3',
          SmallBusinessLegalEssentials: 'ESS',
          SmallBusinessLegalEssentialsBusinessPlusSupplement: 'BPS',
          SmallBusinessLegalPlus: 'PLUS',
          SmallBusinessLegalPlusBusinessPlusSupplement: 'BPS',
          SmallBusinessLegalPlusTrialDefenceforBusiness: 'TDB',
          SmallBusinessLegalPro: 'PRO',
          SmallBusinessLegalProBusinessPlusSupplement: 'BPS',
          SmallBusinessLegalProTrialDefenceforBusiness: 'TDB',
          SuperCommercialDriversLegalPlan: 'SCDLP',
        },
      },
      us: {
        bd: {
          Account: '000000',
          Routing: '103000648',
          name: 'Tester',
          postalCode: '20147',
        },
        cc: {
          cn: '4444333322221111',
          cvv: '111',
          exp: '01/23',
          name: 'Tester',
          postalCode: '20147',
        },
        city: {
          VA: 'Virginia',
        },
      },
    },
  };
}
