/* eslint-disable sort-keys-fix/sort-keys-fix */
/* eslint-disable sort-keys */
export const headerThreeLinksData = [
  {
    testCaseName: 'Verify the Memberships/Personal & Family/Legal Plan Details link',
    associate: 'cartb1all',
    firstLevelLink: 'Memberships',
    secondLevelLink: 'Personal & Family',
    thirdLevelLink: 'Legal Plan Details',
    expectedUrl: 'legalshieldassociate.com/plans/legal',
    disabled: false,
  },
  {
    testCaseName: 'Verify the Memberships/Personal & Family/How it Works link',
    associate: 'cartb1all',
    firstLevelLink: 'Memberships',
    secondLevelLink: 'Personal & Family',
    thirdLevelLink: 'How it Works',
    expectedUrl: 'legalshieldassociate.com/personal-plan/how-it-works',
    disabled: false,
  },
  {
    testCaseName: 'Verify the Memberships/Run a Business/Small Business Plan Details link',
    associate: 'cartb1all',
    firstLevelLink: 'Memberships',
    secondLevelLink: 'Run a Business',
    thirdLevelLink: 'Small Business Plan Details',
    expectedUrl: 'legalshieldassociate.com/smb',
    disabled: false,
  },
  {
    testCaseName: 'Verify the Memberships/Run a Business/How it Works link',
    associate: 'cartb1all',
    firstLevelLink: 'Memberships',
    secondLevelLink: 'Run a Business',
    thirdLevelLink: 'How it Works',
    expectedUrl: 'legalshieldassociate.com/plans/smb/how-it-works',
    disabled: false,
  },
  {
    testCaseName: 'Verify the Memberships/Identity/Legal + Identity Dual Plan link',
    associate: 'cartb1all',
    firstLevelLink: 'Memberships',
    secondLevelLink: 'Identity',
    thirdLevelLink: 'Legal + Identity Dual Plan',
    expectedUrl: 'legalshieldassociate.com/personal-plan/legal-identity',
    disabled: false,
  },
  {
    testCaseName: 'Verify the Memberships/Commercial Drivers/Commercial Drivers Plan Detail link',
    associate: 'cartb1all',
    firstLevelLink: 'Memberships',
    secondLevelLink: 'Commercial Drivers',
    thirdLevelLink: 'Commercial Drivers Plan Details',
    expectedUrl: 'legalshieldassociate.com/commercial-driver',
    disabled: false,
  },
  {
    testCaseName: 'Verify the Personal/Estate Planning/Last Will & Testament link',
    associate: 'cartb1all',
    firstLevelLink: 'Personal',
    secondLevelLink: 'Estate Planning',
    thirdLevelLink: 'Last Will & Testament',
    expectedUrl: 'legalshieldassociate.com/estate-planning/last-will-and-testament',
    disabled: false,
  },
  {
    testCaseName: 'Verify the Personal/Estate Planning/Trusts link',
    associate: 'cartb1all',
    firstLevelLink: 'Personal',
    secondLevelLink: 'Estate Planning',
    thirdLevelLink: 'Trusts',
    expectedUrl: 'legalshieldassociate.com/estate-planning/trusts',
    disabled: false,
  },
  {
    testCaseName: 'Verify the Personal/Add on Coverage/Trial Defense Supplement link',
    associate: 'cartb1all',
    firstLevelLink: 'Personal',
    secondLevelLink: 'Add on Coverage',
    thirdLevelLink: 'Trial Defense Supplement',
    expectedUrl: 'legalshieldassociate.com/trial-defense',
    disabled: false,
  },
  {
    testCaseName: 'Verify the Personal/Add on Coverage/Gun Owners Supplement link',
    associate: 'cartb1all',
    firstLevelLink: 'Personal',
    secondLevelLink: 'Add on Coverage',
    thirdLevelLink: 'Gun Owners Supplement',
    expectedUrl: 'legalshieldassociate.com/gun-supplement',
    disabled: false,
  },
  {
    testCaseName: 'Verify the Personal/Add on Coverage/Home Business Supplement link',
    associate: 'cartb1all',
    firstLevelLink: 'Personal',
    secondLevelLink: 'Add on Coverage',
    thirdLevelLink: 'Home Business Supplement',
    expectedUrl: 'legalshieldassociate.com/home-business',
    disabled: false,
  },
  {
    testCaseName: 'Verify the Personal/Add on Coverage/Rideshare Supplement link',
    associate: 'cartb1all',
    firstLevelLink: 'Personal',
    secondLevelLink: 'Add on Coverage',
    thirdLevelLink: 'Rideshare Supplement',
    expectedUrl: 'legalshieldassociate.com/rideshare',
    disabled: false,
  },
  {
    testCaseName: 'Verify the Business/Add on Coverage/Business Trial Defense Supplement link',
    associate: 'cartb1all',
    firstLevelLink: 'Business',
    secondLevelLink: 'Add on Coverage',
    thirdLevelLink: 'Business Trial Defense Supplement',
    expectedUrl: 'legalshieldassociate.com/plans/trial-defense-business',
    disabled: false,
  },
];

export const headerTwoLinksData = [
  {
    testCaseName: 'Verify the Resources/About Us link',
    associate: 'cartb1all',
    firstLevelLink: 'Resources',
    secondLevelLink: 'About Us',
    expectedUrl: 'legalshieldassociate.com/about',
    disabled: false,
  },
];
