export const legalshieldData = [
  {
    disabled: false,
    language: 'en',
    market: 'US',
    productDetails: [{ cost: '$29.95', name: 'Legal Plan', shortCode: 'LPUS21', term: 'Monthly', type: 'LegalShield' }],
    regions: ['New York'],
    term: 'Monthly',
    termTotal: '$29.95',
    testCaseName: 'Legal Plan, Existing User',
    userType: 'Existing',
  },
  {
    disabled: false,
    language: 'en',
    market: 'US',
    productDetails: [{ cost: '$29.95', name: 'Legal Plan', shortCode: 'LPUS21', term: 'Monthly', type: 'LegalShield' }],
    regions: ['Florida'],
    term: 'Monthly',
    termTotal: '$29.95',
    testCaseName: 'Legal Plan, New User',
    userType: 'New',
  },
  {
    disabled: false,
    language: 'en',
    market: 'US',
    productDetails: [
      { cost: '$29.95', name: 'Legal Plan', shortCode: 'LPUS21', term: 'Monthly', type: 'LegalShield' },
      {
        cost: '$14.95',
        name: 'Home Business Supplement',
        shortCode: 'HB3',
        term: 'Monthly',
        type: 'LegalShield',
      },
      {
        cost: '$14.95',
        name: 'Trial Defense Supplement',
        shortCode: 'TD3',
        term: 'Monthly',
        type: 'LegalShield',
      },

      {
        cost: '$14.95',
        name: 'Gun Owners Supplement',
        shortCode: 'GO2',
        term: 'Monthly',
        type: 'LegalShield',
      },
      {
        cost: '$14.95',
        name: 'Ride Share and Delivery Supplement',
        shortCode: 'RS2',
        term: 'Monthly',
        type: 'LegalShield',
      },
    ],
    regions: ['California'],
    term: 'Monthly',
    termTotal: '$89.75',
    testCaseName: 'Legal Plan, All Supplements',
    userType: 'Existing',
  },
];
