export const shieldAssociateData = [
  {
    disabled: false,
    market: 'United States - English',
    paymentMethod: 'bank draft',
    planDetails: [
      {
        associateRegistrationType: 'NA',
        cost: '$29.95',
        marketingName: 'Family Legal Plan',
        name: 'Legal Plan Family',
        shortCode: 'LPUS21',
        supplementsOrTier: [],
        term: 'Monthly',
        type: 'LegalShield',
      },
    ],
    regions: ['Colorado'],
    termTotal: '$29.95',
    testCaseName: 'Family Legal Plan',
    userType: 'Existing',
  },
  {
    disabled: false,
    market: 'United States - English',
    paymentMethod: 'bank draft',
    planDetails: [
      {
        associateRegistrationType: 'NA',
        cost: '$29.95',
        marketingName: 'Family Legal Plan',
        name: 'Legal Plan Family',
        shortCode: 'LPUS21',
        supplementsOrTier: [
          { cost: '$14.95', name: 'Home Business Supplement' },
          { cost: '$14.95', name: 'Trial Defense Supplement' },
          { cost: '$14.95', name: 'Ride Share & Delivery Drivers Supplement' },
          { cost: '$14.95', name: 'Gun Owners Supplement' },
        ],
        term: 'Monthly',
        type: 'LegalShield',
      },
    ],
    regions: ['Colorado'],
    termTotal: '$89.75',
    testCaseName: 'Family Legal Plan + All Supplements',
    userType: 'Existing',
  },
  {
    disabled: false,
    market: 'United States - English',
    paymentMethod: 'bank draft',
    planDetails: [
      {
        associateRegistrationType: 'NA',
        cost: '$29.95',
        marketingName: 'Family Identity Protection',
        name: 'IDShield Family',
        shortCode: 'TBD',
        supplementsOrTier: [{ cost: '$29.95', name: '1 Bureau Credit Monitoring' }],
        term: 'Monthly',
        type: 'IDShield',
      },
    ],
    regions: ['New York'],
    termTotal: '$29.95',
    testCaseName: 'Family Identity Protection with 1 Bureau Credit Monitoring ',
    userType: 'Existing',
  },
  {
    disabled: false,
    market: 'United States - English',
    paymentMethod: 'bank draft',
    planDetails: [
      {
        associateRegistrationType: 'NA',
        cost: '$34.95',
        marketingName: 'Family Identity Protection',
        name: 'IDShield Family',
        shortCode: 'TBD',
        supplementsOrTier: [{ cost: '$34.95', name: '3 Bureau Credit Monitoring' }],
        term: 'Monthly',
        type: 'IDShield',
      },
    ],
    regions: ['Florida'],
    termTotal: '$34.95',
    testCaseName: 'Family Identity Protection with 3 Bureau Credit Monitoring ',
    userType: 'Existing',
  },
  {
    disabled: false,
    market: 'United States - English',
    paymentMethod: 'bank draft',
    planDetails: [
      {
        associateRegistrationType: 'NA',
        cost: '$14.95',
        marketingName: 'Individual Identity Protection',
        name: 'IDShield Individual',
        shortCode: 'TBD',
        supplementsOrTier: [{ cost: '$14.95', name: '1 Bureau Credit Monitoring' }],
        term: 'Monthly',
        type: 'IDShield',
      },
    ],
    regions: ['Texas'],
    termTotal: '$14.95',
    testCaseName: 'Individual Identity Protection with 1 Bureau Credit Monitoring ',
    userType: 'Existing',
  },
  {
    disabled: false,
    market: 'United States - English',
    paymentMethod: 'bank draft',
    planDetails: [
      {
        associateRegistrationType: 'NA',
        cost: '$19.95',
        marketingName: 'Individual Identity Protection',
        name: 'IDShield Individual',
        shortCode: 'TBD',
        supplementsOrTier: [{ cost: '$19.95', name: '3 Bureau Credit Monitoring' }],
        term: 'Monthly',
        type: 'IDShield',
      },
    ],
    regions: ['California'],
    termTotal: '$19.95',
    testCaseName: 'Individual Identity Protection with 3 Bureau Credit Monitoring ',
    userType: 'Existing',
  },
  {
    disabled: false,
    market: 'United States - English',
    paymentMethod: 'bank draft',
    planDetails: [
      {
        associateRegistrationType: 'NA',
        cost: '$49.00',
        marketingName: 'Small Business',
        name: 'Small Business',
        shortCode: 'TBD',
        supplementsOrTier: [{ cost: '$49.00', name: 'Essentials Plan' }],
        term: 'Monthly',
        type: 'LegalShield',
      },
    ],
    regions: ['Ohio'],
    termTotal: '$49.00',
    testCaseName: 'Small Business Essentials Plan',
    userType: 'Existing',
  },
  {
    disabled: false,
    market: 'United States - English',
    paymentMethod: 'bank draft',
    planDetails: [
      {
        associateRegistrationType: 'NA',
        cost: '$49.00',
        marketingName: 'Small Business',
        name: 'Small Business - Essentials Plan',
        shortCode: 'TBD',
        supplementsOrTier: [
          { cost: '$49.00', name: 'Essentials Plan' },
          { cost: '$14.95', name: 'Business Plus Supplement' },
        ],
        term: 'Monthly',
        type: 'LegalShield',
      },
    ],
    regions: ['Colorado'],
    termTotal: '$63.95',
    testCaseName: 'Small Business Essentials Plan + Business Plus Supplement',
    userType: 'Existing',
  },
  {
    disabled: false,
    market: 'United States - English',
    paymentMethod: 'bank draft',
    planDetails: [
      {
        associateRegistrationType: 'NA',
        cost: '$99.00',
        marketingName: 'Small Business',
        name: 'Small Business',
        shortCode: 'TBD',
        supplementsOrTier: [{ cost: '$99.00', name: 'Plus Plan' }],
        term: 'Monthly',
        type: 'LegalShield',
      },
    ],
    regions: ['New York'],
    termTotal: '$99.00',
    testCaseName: 'Small Business Plus',
    userType: 'Existing',
  },
  {
    disabled: false,
    market: 'United States - English',
    paymentMethod: 'bank draft',
    planDetails: [
      {
        associateRegistrationType: 'NA',
        cost: '$169.00',
        marketingName: 'Small Business',
        name: 'Small Business',
        shortCode: 'TBD',
        supplementsOrTier: [{ cost: '$169.00', name: 'Pro Plan' }],
        term: 'Monthly',
        type: 'LegalShield',
      },
    ],
    regions: ['Georgia'],
    termTotal: '$169.00',
    testCaseName: 'Small Business Pro',
    userType: 'Existing',
  },

  {
    disabled: true, //not available on UAT yet
    market: 'United States - English',
    paymentMethod: 'bank draft',
    planDetails: [
      {
        associateRegistrationType: 'individual',
        cost: '$0.00',
        marketingName: 'Associate',
        name: 'Associate',
        shortCode: 'TBD',
        supplementsOrTier: [],
        term: 'one-time fee',
        type: 'LegalShield',
      },
    ],
    regions: ['Colorado'],
    termTotal: '$0.00',
    testCaseName: 'Associate - Individual',
    userType: 'Existing',
  },
];
